### ISSUE TITLE
default grid column names (A, B, C, ...) should be posible to overwrite?

### ISSUE THREAD

**Issue by brazadas** [datasketch/hotr#36]
i think it could be useful ---especially for the apps-- to overwrite this names so that it can be a guide for the correct content of the column. Moreover, as it establish the correct content of every column there will be no need -- as in the bar chart race app or gender app -- to use selectors so that the user indicates which column has the information needed... Also, it would be good when a user fills the table from scratch 
![Screenshot from 2020-06-08 12-07-48](https://user-images.githubusercontent.com/19413995/84060324-a148ce80-a981-11ea-8ec6-3b7af9653d0a.png)
![Screenshot from 2020-06-08 12-09-30](https://user-images.githubusercontent.com/19413995/84060335-a443bf00-a981-11ea-9e66-19da8a982132.png)

**Comment by jpmarindiaz** [comment]
The reason we have A,B,C is because it is more consistent with the experience of users with spreadsheets. 
Fixing the column names headers for something specific as you suggest may lead to unexpected UI issues because the input table structure has to be fixed, which is something we have avoided. We rather have them more general unless there is a very good reason to leave them fixed.

I do think it is a good idea to add some extra information about the colum (perhaps as a tooltip?) in column name?
![image](https://user-images.githubusercontent.com/1489570/84066181-27b5de00-a98b-11ea-92b9-673b5329c050.png)
Or add as new row?


Empty tables for users to edit is already described in:
https://github.com/datasketch/hotr/issues/33

**Comment by brazadas** [comment]
yes it could be another row with distinctive styles and I think it is better than a tooltip cause it is information that need to be seen all the time
